export type Subject={id:string;name:string;color:string};
export type Task={id:string;subject:string;title:string;description:string;type:string;due:string;priority:string;responsible:string;link:string;members:string[];steps:{id:string;title:string;done:boolean}[]};
export type Message={id:string;task:string;author:string;userId:string;text:string;at:string};
export type ClassData={subjects:Subject[];tasks:Task[];messages:Message[]};
export const types=['Lição de casa','Trabalho','Prova','Aviso'];
export const priorities=['Baixa','Média','Alta'];
export function dateKey(d=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(d)}
export function offsetDate(n:number){const d=new Date();d.setDate(d.getDate()+n);return dateKey(d)}
export function seed():ClassData {const subjects=[['mat','Matemática','#6655df'],['por','Português','#e45588'],['his','História','#d38418'],['geo','Geografia','#138a70'],['cie','Ciências','#2193bc'],['ing','Inglês','#586ad9']].map(([id,name,color])=>({id,name,color}));const rows=[['mat','Equações do 2º grau','Resolver os exercícios 1 a 12 da página 84. Apresentar o desenvolvimento no caderno.','Lição de casa',0,'Alta','Prof. Ricardo'],['por','Resenha de O Pequeno Príncipe','Escrever uma resenha de 20 a 30 linhas com sua opinião sobre a obra.','Trabalho',0,'Média','Profa. Helena'],['cie','Revisão: células e tecidos','Revisar os capítulos 4 e 5. A prova terá questões objetivas e uma questão aberta.','Prova',0,'Alta','Profa. Camila'],['his','Revolução Industrial','Ler o capítulo 6 e responder às questões de interpretação.','Lição de casa',-1,'Média','Prof. André'],['geo','Biomas brasileiros','Preparar apresentação em grupo sobre um bioma, com clima, fauna, flora e ameaças ambientais.','Trabalho',3,'Alta','Profa. Marina'],['ing','Simple past: practice time','Completar a atividade de verbos regulares e irregulares, páginas 32 e 33.','Lição de casa',1,'Baixa','Teacher Ana'],['mat','Avaliação de geometria','Ângulos, triângulos e teorema de Pitágoras. Trazer régua e lápis.','Prova',5,'Alta','Prof. Ricardo'],['cie','Feira de ciências: energia limpa','Construir um modelo e explicar as vantagens de uma fonte renovável.','Trabalho',7,'Média','Profa. Camila'],['por','Roda de leitura','Trazer o livro escolhido para compartilhar um trecho com a turma.','Aviso',2,'Baixa','Profa. Helena']];return {subjects,tasks:rows.map((r,i)=>({id:`demo-${i}`,subject:String(r[0]),title:String(r[1]),description:String(r[2]),type:String(r[3]),due:offsetDate(Number(r[4])),priority:String(r[5]),responsible:String(r[6]),link:'',members:r[3]==='Trabalho'?['Ana','Lucas','Beatriz']:[],steps:r[3]==='Trabalho'?[{id:'research',title:'Pesquisar e reunir referências',done:true},{id:'create',title:'Preparar o material',done:false},{id:'review',title:'Revisar e entregar',done:false}]:[]})),messages:[{id:'welcome',task:'',author:'Mensagem de exemplo',userId:'demo',text:'Bem-vindos ao espaço da turma! Usem este chat para tirar dúvidas e combinar os trabalhos. 📚',at:new Date().toISOString()}]}}
