'use client';
import { useEffect, useState, FormEvent } from 'react';
import { Sun, Sunrise, LayoutGrid, CalendarDays, Users, MessageCircle, Plus, ArrowUpRight, Check, Clock3, Bell, BookOpen, SlidersHorizontal, ChevronLeft, ChevronRight, Paperclip, Send, Pencil, Trash2, GraduationCap, CheckCheck, Settings2 } from 'lucide-react';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction } from '@/components/ui/alert-dialog';
import { SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger } from '@/components/ui/sidebar';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import { Checkbox } from '@/components/ui/checkbox';
import { Tabs,TabsList,TabsTrigger } from '@/components/ui/tabs';
import { Progress } from '@/components/ui/progress';
import { ClassData, Task, Subject, seed, types, priorities,dateKey,offsetDate } from '@/lib/classroom';
type Person={id:string;name:string;role:string};
type Data=ClassData & {me:Person;people:Person[];completed:string[]};
const nav=[['Hoje',Sun],['Amanhã',Sunrise],['Todas',LayoutGrid],['Calendário',CalendarDays],['Trabalhos',Users],['Chat',MessageCircle]] as const;
const STORAGE_KEY='tarefas-da-sala-vercel';
const defaultPerson={id:'local-user',name:'Aluno',role:'Administrador'};
function Choice({value,onChange,options,label}:{value:string;onChange:(s:string)=>void;options:{value:string;label:string}[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>}
const opts=(a:string[])=>a.map(x=>({value:x,label:x}));
function humanDate(s:string){return new Date(s+'T12:00:00').toLocaleDateString('pt-BR',{day:'numeric',month:'short'})}
export default function Home(){
 const [data,setData]=useState<Data|null>(null),[demo]=useState(seed),[tab,setTab]=useState('Hoje'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 const [filter,setFilter]=useState({subject:'all',type:'all',status:'all',date:''}),[selected,setSelected]=useState<string|null>(null),[draft,setDraft]=useState<Task|null>(null),[subjectDraft,setSubjectDraft]=useState<Subject|null>(null),[settings,setSettings]=useState(false),[confirm,setConfirm]=useState<{action:string;id:string;title:string}|null>(null),[message,setMessage]=useState(''),[notifications,setNotifications]=useState(false);
 const [nickname,setNickname]=useState('');
 const [calendar,setCalendar]=useState(new Date()),[calendarMode,setCalendarMode]=useState('month'),[today,setToday]=useState(dateKey());
 const content=data||demo,completed=data?.completed||[],admin=data?.me.role==='Administrador',editor=!!data&&['Administrador','Professor','Representante'].includes(data.me.role);
 const tomorrow=offsetDate(1),dueToday=content.tasks.filter(t=>t.due===today),pending=content.tasks.filter(t=>!completed.includes(t.id)),overdue=pending.filter(t=>t.due<today),upcoming=pending.filter(t=>t.due>today).sort((a,b)=>a.due.localeCompare(b.due)),task=content.tasks.find(t=>t.id===selected);
 function save(next:Data){setData(next);localStorage.setItem(STORAGE_KEY,JSON.stringify(next))}
 useEffect(()=>{try{const saved=localStorage.getItem(STORAGE_KEY);if(saved)setData(JSON.parse(saved) as Data);else setData({...seed(),me:defaultPerson,people:[defaultPerson],completed:[]});setError('')}catch{setData({...seed(),me:defaultPerson,people:[defaultPerson],completed:[]});setError('')}finally{setLoading(false)}const timer=setInterval(()=>setToday(dateKey()),20000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{if(data?.me.name)setNickname(data.me.name)},[data?.me.name]);
 async function act(body:any,success='Alteração salva'){if(!data)return false;setBusy(true);setError('');try{const next=structuredClone(data) as Data;if(body.action==='complete'){next.completed=body.done?[...new Set([...next.completed,body.id])]:next.completed.filter(id=>id!==body.id)}else if(body.action==='nickname'){next.me.name=body.name;next.people=next.people.map(p=>p.id===next.me.id?{...p,name:body.name}:p)}else if(body.action==='message'){next.messages.push({id:crypto.randomUUID(),task:body.task||'',text:body.text,author:next.me.name,userId:next.me.id,at:new Date().toISOString()})}else if(body.action==='role'){next.people=next.people.map(p=>p.id===body.id?{...p,role:body.role}:p)}else if(body.action==='subject'){const i=next.subjects.findIndex(s=>s.id===body.subject.id);if(i<0)next.subjects.push(body.subject);else next.subjects[i]=body.subject}else if(body.action==='deleteSubject'){if(next.tasks.some(t=>t.subject===body.id))throw Error('Mova ou exclua as atividades desta matéria antes de excluí-la.');next.subjects=next.subjects.filter(s=>s.id!==body.id)}else if(body.action==='task'){const i=next.tasks.findIndex(t=>t.id===body.task.id);if(i<0)next.tasks.push(body.task);else next.tasks[i]=body.task}else if(body.action==='deleteTask'){next.tasks=next.tasks.filter(t=>t.id!==body.id);next.messages=next.messages.filter(m=>m.task!==body.id);next.completed=next.completed.filter(id=>id!==body.id)}else if(body.action==='step'){const step=next.tasks.find(t=>t.id===body.id)?.steps.find(s=>s.id===body.step);if(!step)throw Error('Etapa não encontrada');step.done=body.done}else throw Error('Ação inválida');save(next);setNotice(success);return true}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.');return false}finally{setBusy(false)}}
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),4000);return()=>clearTimeout(t)},[notice]);
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const control=new AbortController();Promise.resolve(ctx.registerTool({name:'view_classroom_tab',title:'Abrir aba da turma',description:'Abre Hoje, Amanhã, Todas, Calendário, Trabalhos ou Chat, sem alterar atividades.',inputSchema:{type:'object',properties:{tab:{type:'string',enum:nav.map(x=>x[0])}},required:['tab'],additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:any)=>{if(!nav.some(x=>x[0]===input?.tab))throw Error('Aba inválida');setTab(input.tab);return {tab:input.tab}}},{signal:control.signal})).catch(()=>{});return()=>control.abort()},[]);
 function go(v:string){setTab(v);setFilter({subject:'all',type:'all',status:'all',date:''})}
 function newTask(){setDraft({id:crypto.randomUUID(),title:'',description:'',subject:content.subjects.find(s=>s.name===tab)?.id||content.subjects[0]?.id||'',type:tab==='Trabalhos'?'Trabalho':'Lição de casa',due:tab==='Amanhã'?tomorrow:today,priority:'Média',responsible:'',link:'',members:[],steps:[]})}
 const subject=content.subjects.find(s=>s.name===tab);
 const shown=content.tasks.filter(t=>(tab==='Hoje'?t.due===today:tab==='Amanhã'?t.due===tomorrow:tab==='Trabalhos'?t.type==='Trabalho':subject?t.subject===subject.id:true)&&(filter.subject==='all'||t.subject===filter.subject)&&(filter.type==='all'||t.type===filter.type)&&(!filter.date||t.due===filter.date)&&(filter.status==='all'||(filter.status==='done'?completed.includes(t.id):filter.status==='late'?t.due<today&&!completed.includes(t.id):!completed.includes(t.id)))).sort((a,b)=>a.due.localeCompare(b.due)||Number(completed.includes(a.id))-Number(completed.includes(b.id)));
 const progress=content.tasks.length?Math.round(completed.filter(id=>content.tasks.some(t=>t.id===id)).length/content.tasks.length*100):0;
 function Card({t}:{t:Task}){const s=content.subjects.find(s=>s.id===t.subject),done=completed.includes(t.id);return <article className={'task-card '+(done?'is-done':'')} style={{'--subject':s?.color} as React.CSSProperties}><div className="card-top"><span className="subject-tag">{s?.name}</span><span className={'priority p-'+t.priority}>{t.priority==='Alta'?'↑ ':''}{t.priority}</span></div><div className="task-title"><Checkbox aria-label={'Marcar '+t.title+' como '+(done?'pendente':'feita')} checked={done} disabled={!data||busy} onCheckedChange={v=>act({action:'complete',id:t.id,done:v===true},v?'Atividade marcada como feita, só para você.':'Atividade marcada como pendente.')}/><button onClick={()=>setSelected(t.id)}>{t.title}</button></div><p className="task-description">{t.description}</p><div className="card-meta"><span><BookOpen size={14}/>{t.type}</span><span>{content.messages.filter(m=>m.task===t.id).length>0&&<><MessageCircle size={14}/>{content.messages.filter(m=>m.task===t.id).length}</>}</span></div>{tab==='Trabalhos'&&<div className="group-progress"><div><span>{t.members.join(', ')||'Membros a definir'}</span><b>{t.steps.filter(s=>s.done).length}/{t.steps.length} etapas</b></div><Progress value={t.steps.length?t.steps.filter(s=>s.done).length/t.steps.length*100:0}/></div>}<footer><span className={!done&&t.due<today?'late':''}><Clock3 size={14}/>{done?'Concluída':t.due===today?'Entrega hoje':t.due===tomorrow?'Entrega amanhã':humanDate(t.due)}{!done&&t.due<today?' · atrasada':''}</span><button aria-label={'Ver detalhes de '+t.title} onClick={()=>setSelected(t.id)}><ArrowUpRight size={18}/></button></footer></article>}
 async function send(e:FormEvent,taskId=''){e.preventDefault();if(await act({action:'message',task:taskId,text:message},'Mensagem enviada'))setMessage('')}
 function Messages({taskId=''}:{taskId?:string}){const list=content.messages.filter(m=>m.task===taskId);return <><div className="messages">{!list.length&&<div className="empty">Comece a conversa. Tire uma dúvida ou compartilhe uma ideia.</div>}{list.map(m=><article key={m.id} className={'message '+(m.userId===data?.me.id?'mine':'')}><span className="avatar">{m.author.slice(0,1).toUpperCase()}</span><div><header><b>{m.author}</b><time>{new Date(m.at).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</time></header><p>{m.text}</p></div></article>)}</div></>}
 function compose(taskId=''){return <form className="compose" onSubmit={e=>send(e,taskId)}><input aria-label={taskId?'Seu comentário':'Mensagem para a turma'} placeholder={taskId?'Escreva um comentário…':'Escreva para a turma…'} value={message} onChange={e=>setMessage(e.target.value)} required maxLength={2000} disabled={!data}/><button className="primary icon" aria-label="Enviar mensagem" disabled={!data||busy||!message.trim()}><Send size={18}/></button></form>}
 const calStart=new Date(calendar.getFullYear(),calendar.getMonth(),1,12);calStart.setDate(calStart.getDate()-((calStart.getDay()+6)%7));if(calendarMode==='week'){calStart.setFullYear(calendar.getFullYear(),calendar.getMonth(),calendar.getDate());calStart.setDate(calStart.getDate()-((calStart.getDay()+6)%7))}
 const days=Array.from({length:calendarMode==='week'?7:42},(_,i)=>{const d=new Date(calStart);d.setDate(d.getDate()+i);return d});
 return <SidebarProvider><Sidebar className="class-sidebar"><SidebarHeader><div className="brand"><span className="brand-icon"><GraduationCap size={25}/></span><div><b>Tarefas da Sala</b><small>Nosso espaço de organização</small></div></div></SidebarHeader><SidebarContent><div className="nav-label">PAINEL DA TURMA</div><SidebarMenu>{nav.map(([name,Icon])=><SidebarMenuItem key={name}><SidebarMenuButton isActive={tab===name} onClick={()=>go(name)}><Icon/><span>{name}</span>{name==='Hoje'&&<em>{dueToday.length}</em>}{name==='Amanhã'&&<em>{content.tasks.filter(t=>t.due===tomorrow).length}</em>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="nav-label">MATÉRIAS {admin&&<button aria-label="Adicionar matéria" onClick={()=>setSubjectDraft({id:crypto.randomUUID(),name:'',color:'#6655df'})}><Plus size={17}/></button>}</div><SidebarMenu>{content.subjects.map(s=><SidebarMenuItem key={s.id}><SidebarMenuButton isActive={tab===s.name} onClick={()=>go(s.name)}><span className="subject-dot" style={{background:s.color}}/><span>{s.name}</span><small>{content.tasks.filter(t=>t.subject===s.id&&!completed.includes(t.id)).length}</small></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarContent><SidebarFooter><div className="sidebar-note"><BookOpen size={20}/><b>Um passo de cada vez.</b><p>Organize hoje, facilite o amanhã.</p></div><button className="profile" onClick={()=>setSettings(true)}><span className="avatar">{data?.me.name.slice(0,1).toUpperCase()||'T'}</span><span><b>{data?.me.name||'Sua turma'}</b><small>{data?.me.role||'Prévia do painel'}</small></span><Settings2 size={17}/></button></SidebarFooter></Sidebar>
 <main className="main"><header className="topbar"><div className="top-left"><SidebarTrigger/><span>Painel da turma <span className="slash">/</span> <b>{tab}</b></span></div><div className="top-right"><span className="today-date">{new Date(today+'T12:00:00').toLocaleDateString('pt-BR',{weekday:'long',day:'numeric',month:'long'})}</span><button className="bell" aria-label="Ver notificações de entregas" onClick={()=>setNotifications(true)}><Bell size={20}/>{pending.some(t=>t.due<=tomorrow)&&<i/>}</button><span className="avatar small">{data?.me.name.slice(0,1).toUpperCase()||'T'}</span></div></header>
 <div className="workspace"><div className="page-heading"><div><span className="eyebrow">TUDO EM DIA, DO SEU JEITO</span><h1>{tab==='Hoje'?'Vamos organizar o dia?':tab==='Amanhã'?'Um passo à frente.':tab}</h1><p>{tab==='Hoje'?'Veja o que precisa da sua atenção hoje.':tab==='Amanhã'?'Prepare-se para as entregas de amanhã.':tab==='Chat'?'Um espaço para dúvidas, ideias e combinados.':'As atividades da turma, sempre por perto.'}</p></div>{editor&&tab!=='Chat'&&<button className="primary" onClick={newTask}><Plus size={18}/>Nova atividade</button>}</div>
 {(error||loading)&&<div className="status-banner" role="status">{loading?'Preparando o painel…':error}</div>}
 {notice&&<div className="toast" role="status"><Check size={18}/>{notice}</div>}
 <section className="stats"><button onClick={()=>go('Hoje')} className="stat"><span className="stat-icon purple"><Sun/></span><div><span>Para hoje</span><b>{dueToday.length.toString().padStart(2,'0')}</b></div><small>Vamos lá!</small></button><button onClick={()=>{go('Todas');setFilter(f=>({...f,status:'pending'}))}} className="stat"><span className="stat-icon orange"><Clock3/></span><div><span>Pendentes</span><b>{pending.length.toString().padStart(2,'0')}</b></div><small>Uma de cada vez</small></button><button onClick={()=>{go('Todas');setFilter(f=>({...f,status:'done'}))}} className="stat"><span className="stat-icon green"><CheckCheck/></span><div><span>Concluídas por você</span><b>{completed.filter(id=>content.tasks.some(t=>t.id===id)).length.toString().padStart(2,'0')}</b></div><small>Continue assim</small></button></section>
 <div className={'content-grid '+(['Calendário','Chat','Trabalhos'].includes(tab)?'wide':'')}><section className="activity-area">
 {tab==='Calendário'?<div className="calendar-panel"><header className="section-heading"><h2>{calendar.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</h2><div className="calendar-controls"><button aria-label="Período anterior" onClick={()=>setCalendar(d=>calendarMode==='month'?new Date(d.getFullYear(),d.getMonth()-1,1,12):new Date(d.getFullYear(),d.getMonth(),d.getDate()-7,12))}><ChevronLeft/></button><button onClick={()=>setCalendar(new Date())}>Hoje</button><button aria-label="Próximo período" onClick={()=>setCalendar(d=>calendarMode==='month'?new Date(d.getFullYear(),d.getMonth()+1,1,12):new Date(d.getFullYear(),d.getMonth(),d.getDate()+7,12))}><ChevronRight/></button></div></header><Tabs value={calendarMode} onValueChange={setCalendarMode}><TabsList><TabsTrigger value="month">Mês</TabsTrigger><TabsTrigger value="week">Semana</TabsTrigger></TabsList></Tabs><div className={'calendar-grid '+calendarMode}>{['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'].map(d=><div className="weekday" key={d}>{d}</div>)}{days.map(d=>{const key=dateKey(d);return <div className={'calendar-cell '+(d.getMonth()!==calendar.getMonth()?'muted-day ':'')+(key===today?'current':'')} key={key}><span>{d.getDate()}</span>{content.tasks.filter(t=>t.due===key).map(t=><button key={t.id} onClick={()=>setSelected(t.id)} style={{borderLeftColor:content.subjects.find(s=>s.id===t.subject)?.color}}>{t.title}</button>)}</div>})}</div></div>:tab==='Chat'?<div className="chat-panel"><header className="section-heading"><h2><MessageCircle size={20}/>Chat da turma</h2><span>Atualização automática</span></header><Messages/>{compose()}</div>:<>
 <div className="section-heading"><h2>{tab==='Hoje'?'Entregas de hoje':tab==='Amanhã'?'Entregas de amanhã':tab==='Todas'?'Todas as atividades':tab==='Trabalhos'?'Trabalhos em grupo':tab}<span className="count">{shown.length}</span></h2>{subject&&admin&&<button className="text-button" onClick={()=>setSubjectDraft({...subject})}><Pencil size={15}/>Editar matéria</button>}<SlidersHorizontal size={18} className="filter-icon"/></div>
 <div className="filters">{!subject&&<Choice value={filter.subject} onChange={v=>setFilter({...filter,subject:v})} label="Filtrar por matéria" options={[{value:'all',label:'Todas as matérias'},...content.subjects.map(s=>({value:s.id,label:s.name}))]}/>}<Choice value={filter.type} onChange={v=>setFilter({...filter,type:v})} label="Filtrar por tipo" options={[{value:'all',label:'Todos os tipos'},...opts(types)]}/><Choice value={filter.status} onChange={v=>setFilter({...filter,status:v})} label="Filtrar por status" options={[{value:'all',label:'Todos os status'},{value:'pending',label:'Pendentes'},{value:'done',label:'Concluídas'},{value:'late',label:'Atrasadas'}]}/>{!['Hoje','Amanhã'].includes(tab)&&<input type="date" aria-label="Filtrar por data" value={filter.date} onChange={e=>setFilter({...filter,date:e.target.value})}/>}</div>
 <div className="task-grid">{shown.map(t=><Card key={t.id} t={t}/>)}</div>{!shown.length&&<div className="empty"><span className="empty-icon"><CheckCheck size={30}/></span><h3>{tab==='Hoje'?'Nenhuma entrega para hoje.':tab==='Amanhã'?'Nenhuma entrega para amanhã.':'Nenhuma atividade por aqui.'}</h3><p>Aproveite para se organizar.{filter.status!=='all'||filter.type!=='all'||filter.subject!=='all'||filter.date?' Experimente ajustar os filtros.':''}</p></div>}
 {tab==='Hoje'&&overdue.length>0&&<section className="overdue-section"><div className="section-heading"><h2><Clock3 size={19}/>Ainda dá tempo de resolver <span className="count">{overdue.length}</span></h2></div>{overdue.map(t=><button className="overdue-row" key={t.id} onClick={()=>setSelected(t.id)}><span className="subject-dot" style={{background:content.subjects.find(s=>s.id===t.subject)?.color}}/><div><b>{t.title}</b><small>{content.subjects.find(s=>s.id===t.subject)?.name}</small></div><span className="late">{humanDate(t.due)} · atrasada</span><ArrowUpRight size={18}/></button>)}</section>}
 </>}
 </section>{!['Calendário','Chat','Trabalhos'].includes(tab)&&<aside className="right-rail"><section className="progress-panel"><div className="section-heading"><h2>Seu ritmo</h2><span className="spark">✦</span></div><div className="progress-ring" style={{'--progress':progress+'%'} as React.CSSProperties}><div><b>{progress}%</b><span>concluído</span></div></div><h3>{progress===100?'Tudo em dia!':'Cada tarefa conta.'}</h3><p>Seu progresso é só seu.<br/>Marque o que já finalizou.</p></section><section className="upcoming-panel"><div className="section-heading"><h2>Próximas entregas</h2><CalendarDays size={18}/></div>{upcoming.slice(0,4).map(t=><button className="upcoming-item" key={t.id} onClick={()=>setSelected(t.id)}><span className="date-tile"><b>{new Date(t.due+'T12:00:00').getDate()}</b><small>{new Date(t.due+'T12:00:00').toLocaleDateString('pt-BR',{month:'short'}).replace('.','')}</small></span><span><b>{t.title}</b><small style={{color:content.subjects.find(s=>s.id===t.subject)?.color}}>{content.subjects.find(s=>s.id===t.subject)?.name}</small></span></button>)}{!upcoming.length&&<p className="muted">Nenhuma entrega próxima.</p>}<button className="text-button calendar-link" onClick={()=>go('Calendário')}>Ver calendário completo <ArrowUpRight size={16}/></button></section><div className="team-note"><Users size={21}/><span>Juntos, a rotina fica mais leve.</span></div></aside>}</div><footer className="page-footer">Tarefas da Sala<span>Menos correria. Mais organização.</span></footer></div></main>
 <Dialog open={!!task} onOpenChange={v=>{if(!v){setSelected(null);setMessage('')}}}><DialogContent className="detail-modal"><DialogTitle>{task?.title}</DialogTitle><DialogDescription>Detalhes da atividade e conversa da turma.</DialogDescription>{task&&<><div className="detail-tags"><span className="subject-tag" style={{color:content.subjects.find(s=>s.id===task.subject)?.color}}>{content.subjects.find(s=>s.id===task.subject)?.name}</span><span>{task.type}</span><span className={'priority p-'+task.priority}>{task.priority}</span></div><p className="description-full">{task.description||'Nenhuma descrição adicionada.'}</p><div className="detail-info"><span><CalendarDays size={17}/>Entrega: {humanDate(task.due)}</span><span><Users size={17}/>{task.responsible||'Responsável não definido'}</span></div>{task.link&&<a className="attachment" href={task.link} target="_blank" rel="noopener noreferrer"><Paperclip size={18}/>Abrir link ou anexo <ArrowUpRight size={16}/></a>}{task.type==='Trabalho'&&<section className="steps"><h3>Membros do grupo</h3><p>{task.members.join(', ')||'Ainda não definidos'}</p><h3>Etapas do trabalho</h3>{task.steps.map(s=><label key={s.id}><Checkbox checked={s.done} disabled={!editor||busy} onCheckedChange={v=>act({action:'step',id:task.id,step:s.id,done:v===true})}/>{s.title}</label>)}{!task.steps.length&&<p>Nenhuma etapa cadastrada.</p>}</section>}<div className="detail-actions"><button className="primary" disabled={!data||busy} onClick={()=>act({action:'complete',id:task.id,done:!completed.includes(task.id)})}><Check size={17}/>{completed.includes(task.id)?'Feita por mim · desfazer':'Marcar como feita'}</button>{editor&&<><button className="secondary" onClick={()=>{setDraft(structuredClone(task));setSelected(null)}}><Pencil size={16}/>Editar</button><button className="danger icon" aria-label="Excluir atividade" onClick={()=>setConfirm({action:'deleteTask',id:task.id,title:'Excluir esta atividade e seus comentários?'})}><Trash2 size={18}/></button></>}</div>{error&&<p role="alert" className="form-error">{error}</p>}<h3>Comentários</h3><Messages taskId={task.id}/>{compose(task.id)}</>}</DialogContent></Dialog>
 <Dialog open={!!draft} onOpenChange={v=>{if(!v)setDraft(null)}}><DialogContent className="form-modal"><DialogTitle>{content.tasks.some(t=>t.id===draft?.id)?'Editar atividade':'Nova atividade'}</DialogTitle><DialogDescription>Compartilhe uma entrega ou aviso com a turma.</DialogDescription>{draft&&<form onSubmit={async e=>{e.preventDefault();if(await act({action:'task',task:{...draft,members:draft.members.map(s=>s.trim()).filter(Boolean)}}))setDraft(null)}} className="editor-form"><label>Título<input required maxLength={160} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="O que a turma precisa fazer?"/></label><label>Descrição<textarea value={draft.description} maxLength={6000} onChange={e=>setDraft({...draft,description:e.target.value})} placeholder="Orientações, páginas e detalhes da entrega"/></label><div className="form-grid"><label>Matéria<Choice label="Matéria" value={draft.subject} onChange={v=>setDraft({...draft,subject:v})} options={content.subjects.map(s=>({value:s.id,label:s.name}))}/></label><label>Tipo<Choice label="Tipo de atividade" value={draft.type} onChange={v=>setDraft({...draft,type:v})} options={opts(types)}/></label><label>Data de entrega<input type="date" required value={draft.due} onChange={e=>setDraft({...draft,due:e.target.value})}/></label><label>Prioridade<Choice label="Prioridade" value={draft.priority} onChange={v=>setDraft({...draft,priority:v})} options={opts(priorities)}/></label></div><label>Responsável<input value={draft.responsible} maxLength={160} onChange={e=>setDraft({...draft,responsible:e.target.value})} placeholder="Professor, representante ou aluno"/></label><label>Link ou anexo<input value={draft.link} onChange={e=>setDraft({...draft,link:e.target.value})} placeholder="Cole um link do Drive, Classroom ou outro material"/></label>{draft.type==='Trabalho'&&<><label>Membros (separados por vírgula)<input value={draft.members.join(',')} onChange={e=>setDraft({...draft,members:e.target.value.split(',')})} placeholder="Ana, Lucas, Beatriz"/></label><label>Etapas do trabalho</label>{draft.steps.map((s,i)=><div className="step-edit" key={s.id}><input aria-label={'Etapa '+(i+1)} required value={s.title} onChange={e=>setDraft({...draft,steps:draft.steps.map(x=>x.id===s.id?{...x,title:e.target.value}:x)})}/><button type="button" aria-label="Remover etapa" onClick={()=>setDraft({...draft,steps:draft.steps.filter(x=>x.id!==s.id)})}><Trash2 size={16}/></button></div>)}<button type="button" className="secondary" onClick={()=>setDraft({...draft,steps:[...draft.steps,{id:crypto.randomUUID(),title:'',done:false}]})}><Plus size={16}/>Adicionar etapa</button></>}{error&&<p role="alert" className="form-error">{error}</p>}<button disabled={busy||!draft.subject} className="primary">{busy?'Salvando…':'Salvar atividade'}</button></form>}</DialogContent></Dialog>
 <Dialog open={!!subjectDraft} onOpenChange={v=>{if(!v)setSubjectDraft(null)}}><DialogContent><DialogTitle>{content.subjects.some(s=>s.id===subjectDraft?.id)?'Editar matéria':'Nova matéria'}</DialogTitle><DialogDescription>Escolha um nome e uma cor para a matéria.</DialogDescription>{subjectDraft&&<form className="editor-form" onSubmit={async e=>{e.preventDefault();if(await act({action:'subject',subject:subjectDraft})){setSubjectDraft(null);go(subjectDraft.name)}}}><label>Nome<input required maxLength={160} value={subjectDraft.name} onChange={e=>setSubjectDraft({...subjectDraft,name:e.target.value})}/></label><label>Cor<input type="color" value={subjectDraft.color} onChange={e=>setSubjectDraft({...subjectDraft,color:e.target.value})}/></label><button className="primary" disabled={busy}>Salvar matéria</button>{content.subjects.some(s=>s.id===subjectDraft.id)&&<button type="button" className="danger" onClick={()=>setConfirm({action:'deleteSubject',id:subjectDraft.id,title:'Excluir esta matéria? As atividades precisam ser movidas ou excluídas primeiro.'})}><Trash2 size={17}/>Excluir matéria</button>}{error&&<p className="form-error">{error}</p>}</form>}</DialogContent></Dialog>
 <Dialog open={settings} onOpenChange={setSettings}><DialogContent><DialogTitle>Pessoas e permissões</DialogTitle><DialogDescription>Escolha como seu nome aparece no painel, nos comentários e no chat.</DialogDescription>{data&&<form className="nickname-form" onSubmit={async e=>{e.preventDefault();const name=nickname.trim();if(name&&await act({action:'nickname',name},'Nickname atualizado'))setNickname(name)}}><label>Seu nickname<input required maxLength={160} value={nickname} onChange={e=>setNickname(e.target.value)} placeholder="Como você quer aparecer?"/></label><button className="primary" disabled={busy||!nickname.trim()}>Salvar nickname</button></form>}{data?.people.map(p=><div className="person-row" key={p.id}><span><b>{p.name}</b>{p.id===data.me.id&&<small>Você</small>}</span>{admin&&p.id!==data.me.id?<Choice label={'Permissão de '+p.name} value={p.role} onChange={role=>act({action:'role',id:p.id,role})} options={opts(['Aluno','Representante','Professor','Administrador'])}/>:<span className="muted">{p.role}</span>}</div>)}{data&&<p className="muted">Nesta versão gratuita, os dados ficam salvos no navegador deste aparelho.</p>}</DialogContent></Dialog>
 <Dialog open={notifications} onOpenChange={setNotifications}><DialogContent><DialogTitle>Fique de olho</DialogTitle><DialogDescription>Entregas atrasadas, de hoje e de amanhã ainda pendentes para você.</DialogDescription>{pending.filter(t=>t.due<=tomorrow).sort((a,b)=>a.due.localeCompare(b.due)).map(t=><button className="notification-row" key={t.id} onClick={()=>{setNotifications(false);setSelected(t.id)}}><Bell size={18}/><span><b>{t.title}</b><small>{t.due<today?'Atrasada':t.due===today?'Entrega hoje':'Entrega amanhã'} · {t.priority}</small></span><ArrowUpRight size={18}/></button>)}{!pending.some(t=>t.due<=tomorrow)&&<div className="empty">Tudo tranquilo. Nenhuma entrega urgente!</div>}</DialogContent></Dialog>
 <AlertDialog open={!!confirm} onOpenChange={v=>{if(!v)setConfirm(null)}}><AlertDialogContent><AlertDialogTitle>{confirm?.title}</AlertDialogTitle><AlertDialogDescription>Esta ação não pode ser desfeita.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction onClick={async()=>{if(confirm&&await act({action:confirm.action,id:confirm.id})){setSelected(null);setSubjectDraft(null);go('Hoje')}setConfirm(null)}}>Excluir</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </SidebarProvider>
}


