import { db,viewer,state,change,failure } from '@/lib/server-classroom';
import { z } from 'zod';
const short=z.string().trim().min(1).max(160);
const taskSchema=z.object({id:short,subject:short,title:short,description:z.string().max(6000),type:z.enum(['Lição de casa','Trabalho','Prova','Aviso']),due:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>!isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v),priority:z.enum(['Baixa','Média','Alta']),responsible:z.string().max(160),link:z.string().max(2000).refine(v=>!v||/^https?:\/\//i.test(v)||/^\/api\/files\/[a-zA-Z0-9-]+$/.test(v),'Use um link http ou https.'),members:z.array(short).max(40),steps:z.array(z.object({id:short,title:short,done:z.boolean()})).max(50)});
export async function GET(){try{const me=await viewer();if(!me)throw new Error('AUTH');const s=await state();const completed=await db().prepare('SELECT task_id FROM completions WHERE user_id=?').bind(me.id).all<{task_id:string}>();const people=await db().prepare('SELECT id,name,role FROM members ORDER BY name').all();return Response.json({...s.data,me,people:people.results,completed:completed.results.map(r=>r.task_id)},{headers:{'Cache-Control':'no-store'}});}catch(e){return failure(e)}}
export async function POST(req:Request){try{if(req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin)throw new Error('Origem inválida');const me=await viewer();if(!me)throw new Error('AUTH');const b=z.record(z.any()).parse(await req.json()); if(b.id!==undefined)short.parse(b.id);const editor=['Administrador','Professor','Representante'].includes(me.role);const admin=me.role==='Administrador';
if(b.action==='complete'){const id=short.parse(b.id);const done=z.boolean().parse(b.done);const s=await state();if(!s.data.tasks.some(t=>t.id===id))throw new Error('Atividade não encontrada');if(done)await db().prepare('INSERT OR IGNORE INTO completions (id,user_id,task_id) VALUES (?,?,?)').bind(me.id+':'+id,me.id,id).run();else await db().prepare('DELETE FROM completions WHERE user_id=? AND task_id=?').bind(me.id,id).run();}
else if(b.action==='nickname'){const name=short.parse(b.name);await db().prepare('UPDATE members SET name=? WHERE id=?').bind(name,me.id).run();}
else if(b.action==='message'){const text=z.string().trim().min(1).max(2000).parse(b.text);const task=z.string().max(160).parse(b.task??'');await change(s=>{if(task&&!s.tasks.some(t=>t.id===task))throw new Error('Atividade não encontrada');s.messages.push({id:crypto.randomUUID(),task,text,author:me.name,userId:me.id,at:new Date().toISOString()});});}
else if(b.action==='role'){if(!admin)throw new Error('Apenas administradores gerenciam permissões');const id=short.parse(b.id);if(id===me.id)throw new Error('Você não pode alterar sua própria permissão');const role=z.enum(['Administrador','Professor','Representante','Aluno']).parse(b.role);await db().prepare('UPDATE members SET role=? WHERE id=?').bind(role,id).run();}
else if(b.action==='subject'){if(!admin)throw new Error('Apenas administradores gerenciam matérias');const subject=z.object({id:short,name:short,color:z.string().regex(/^#[0-9a-f]{6}$/i)}).parse(b.subject);await change(s=>{if(['Hoje','Amanhã','Todas','Calendário','Trabalhos','Chat'].some(n=>n.toLowerCase()===subject.name.toLowerCase())||s.subjects.some(x=>x.id!==subject.id&&x.name.toLowerCase()===subject.name.toLowerCase()))throw new Error('Escolha um nome diferente para a matéria');const i=s.subjects.findIndex(x=>x.id===subject.id);if(i<0)s.subjects.push(subject);else s.subjects[i]=subject;});}
else if(b.action==='deleteSubject'){if(!admin)throw new Error('Apenas administradores gerenciam matérias');await change(s=>{if(s.tasks.some(t=>t.subject===b.id))throw new Error('Mova ou exclua as atividades desta matéria antes de excluí-la.');s.subjects=s.subjects.filter(x=>x.id!==b.id);});}
else {if(!editor)throw new Error('Somente professores e representantes podem alterar atividades');if(b.action==='task'){const t=taskSchema.parse(b.task);await change(s=>{if(!s.subjects.some(x=>x.id===t.subject))throw new Error('Escolha uma matéria válida');const i=s.tasks.findIndex(x=>x.id===t.id);if(i<0)s.tasks.push(t);else s.tasks[i]=t;});}else if(b.action==='deleteTask'){await change(s=>{s.tasks=s.tasks.filter(t=>t.id!==b.id);s.messages=s.messages.filter(m=>m.task!==b.id);});await db().prepare('DELETE FROM completions WHERE task_id=?').bind(b.id).run();}else if(b.action==='step'){await change(s=>{const step=s.tasks.find(t=>t.id===b.id)?.steps.find(x=>x.id===b.step);if(!step)throw new Error('Etapa não encontrada');step.done=z.boolean().parse(b.done);});}else throw new Error('Ação inválida');}return Response.json({ok:true});}catch(e){return failure(e)}}

